project:
  type: website
  pre-render: generate-cars.R
  render:
    - "*.qmd"
    - "!template.qmd"

website:
  title: "Cars website"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: cars.qmd
        text: Cars

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



