project:
  type: website

website:
  title: "Cars website"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: cars.qmd
        text: Cars

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



